menu:
    Blog: /
    About: /about
    GitHub: https://github.com/p7e4
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Copyright Infomation
startyear: 2022
